/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author oombo
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
    
private void setImage(javax.swing.JLabel label, String imagePath) {
    if (label == null) {
        System.err.println("JLabel is null for path: " + imagePath);
        return;
    }

    java.net.URL imgUrl = getClass().getResource(imagePath);
    if (imgUrl != null) {
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);

        java.awt.Image scaledImage = icon.getImage().getScaledInstance(
            label.getWidth(),
            label.getHeight(),
            java.awt.Image.SCALE_SMOOTH
        );
        // ------------------------------------

        label.setIcon(new javax.swing.ImageIcon(scaledImage));

    } else {
        System.err.println("Image not found: " + imagePath);
    }
}

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        loadUserProfile();
        setImage(jLabel1,"/Images/UserIcon.png");
    }
    
    private void loadUserProfile() {
        String loggedInEmail = Project.Loginnew.loggedInUserEmail;

        if (loggedInEmail == null || loggedInEmail.isEmpty()) {
            jLabel5.setText("Email: Not logged in");
            jLabel4.setText("Date of Creation: Not available");
            return;
        }


        jLabel4.setText("Email: " + loggedInEmail);

        String creationDate = "Date not found"; 
        String filePath = "account.txt";

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] userData = line.split(","); 
                if (userData.length >= 3 && userData[0].equals(loggedInEmail)) {
                    creationDate = userData[2]; 
                    break; 
                }
            }
        } catch (IOException e) {
            creationDate = "Error reading file";
            e.printStackTrace();
        }

        jLabel5.setText("Date of Creation: " + creationDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton8.setForeground(new java.awt.Color(255, 0, 51));
        jButton8.setText("< Main Menu");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setText("🛒");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("┇");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Profile");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("10/10/2006");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Project.Loginnew.userIsLoggedIn) {
            new Cart().setVisible(true);
            this.dispose();
        } else {

            javax.swing.JOptionPane.showMessageDialog(this, "Please log in to access your cart.");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        javax.swing.JPopupMenu popupMenu = new javax.swing.JPopupMenu();

        javax.swing.JMenuItem historyItem = new javax.swing.JMenuItem("Order History");
        javax.swing.JMenuItem reportItem = new javax.swing.JMenuItem("Report");

        popupMenu.add(historyItem);
        popupMenu.add(reportItem );
        popupMenu.add(new javax.swing.JPopupMenu.Separator()); // This adds the line

        historyItem.addActionListener(e -> {
            if (Project.Loginnew.userIsLoggedIn) {
                System.out.println("Order History clicked");
                History history = new History();
                history.setVisible(true);
                this.dispose();
            }else {
                javax.swing.JOptionPane.showMessageDialog(this, "Please log in to access Order History.");
            }
        });

        reportItem.addActionListener(e -> {
            Report report = new Report();
            report.setVisible(true);
            this.dispose();
            System.out.println("Report clicked");
        });

        if (Project.Loginnew.userIsLoggedIn) {
            popupMenu.add(new javax.swing.JPopupMenu.Separator());
            javax.swing.JMenuItem logoutItem = new javax.swing.JMenuItem("Logout");
            popupMenu.add(logoutItem);
            logoutItem.addActionListener(e -> {
                int response = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to log out?", "Confirm Logout",
                    javax.swing.JOptionPane.YES_NO_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE);

                if (response == javax.swing.JOptionPane.YES_OPTION) {
                    Cart.clearCurrentUserCart();
                    Project.Loginnew.userIsLoggedIn = false;
                    Project.Loginnew.loggedInUserEmail = null;
                    new Project.Loginnew().setVisible(true);
                }
            });
        }

        popupMenu.show(jButton6, 0, jButton6.getHeight());
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
